### ISSUE TITLE
Wrong error given when there is a broken link

### ISSUE THREAD

**Issue by GnidaKid69** [danm/image-hash#17]
I get this error when I am trying to hash large array of image URLs and save them into database.

```
if (err) throw err
                                                                                                                 ^

Error: Mime type not found
    at checkFileType (/home/nika/Desktop/test/node_modules/image-hash/lib/imageHash.js:39:16)
    at Request.handleRequest [as _callback] (/home/nika/Desktop/test/node_modules/image-hash/lib/imageHash.js:77:13)
    at Request.self.callback (/home/nika/Desktop/testr/node_modules/request/request.js:185:22)
    at Request.emit (events.js:209:13)
    at Request.<anonymous> (/home/nika/Desktoptest/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:209:13)
    at IncomingMessage.<anonymous> (/home/nika/Desktop/test/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:297:20)
    at IncomingMessage.emit (events.js:214:15)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by GnidaKid69** [comment]
Some of the image links were broken

**Comment by danm** [comment]
thanks @GnidaKid69 for updating. I've modified the issue so that we give a more helpful error message when there is a 404 or something simular.
